build:
	./ns3 configure -d debug --enable-examples --enable-tests
	./ns3 build

parallelTopology:
	./ns3 run scratch/parallel-cross-traffic

alternativeTopology:
	./ns3 run scratch/alternative-topology