# CMake generated Testfile for 
# Source directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/udp-client-server
# Build directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/cmake-cache/examples/udp-client-server
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-udp-client-server "ns3.39-udp-client-server-debug")
set_tests_properties(ctest-udp-client-server PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/examples/udp-client-server/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/udp-client-server/CMakeLists.txt;1;build_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/udp-client-server/CMakeLists.txt;0;")
add_test(ctest-udp-trace-client-server "ns3.39-udp-trace-client-server-debug")
set_tests_properties(ctest-udp-trace-client-server PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/examples/udp-client-server/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/udp-client-server/CMakeLists.txt;10;build_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/udp-client-server/CMakeLists.txt;0;")
