# CMake generated Testfile for 
# Source directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/examples/energy
# Build directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/cmake-cache/examples/energy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-energy-model-example "ns3.39-energy-model-example-debug")
set_tests_properties(ctest-energy-model-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/examples/energy/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/examples/energy/CMakeLists.txt;1;build_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/examples/energy/CMakeLists.txt;0;")
add_test(ctest-energy-model-with-harvesting-example "ns3.39-energy-model-with-harvesting-example-debug")
set_tests_properties(ctest-energy-model-with-harvesting-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/examples/energy/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/examples/energy/CMakeLists.txt;13;build_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/examples/energy/CMakeLists.txt;0;")
