# CMake generated Testfile for 
# Source directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples
# Build directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/cmake-cache/src/csma/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-csma-one-subnet "ns3.39-csma-one-subnet-debug")
set_tests_properties(ctest-csma-one-subnet PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/src/csma/examples/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;11;build_lib_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-broadcast "ns3.39-csma-broadcast-debug")
set_tests_properties(ctest-csma-broadcast PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/src/csma/examples/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;11;build_lib_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-packet-socket "ns3.39-csma-packet-socket-debug")
set_tests_properties(ctest-csma-packet-socket PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/src/csma/examples/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;11;build_lib_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-multicast "ns3.39-csma-multicast-debug")
set_tests_properties(ctest-csma-multicast PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/src/csma/examples/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;11;build_lib_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-raw-ip-socket "ns3.39-csma-raw-ip-socket-debug")
set_tests_properties(ctest-csma-raw-ip-socket PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/src/csma/examples/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;21;build_lib_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-ping "ns3.39-csma-ping-debug")
set_tests_properties(ctest-csma-ping PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/src/csma/examples/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;31;build_lib_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/src/csma/examples/CMakeLists.txt;0;")
