# CMake generated Testfile for 
# Source directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples
# Build directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.39-time-probe-example-debug")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;1;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.39-gnuplot-example-debug")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.39-double-probe-example-debug")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.39-gnuplot-aggregator-example-debug")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.39-gnuplot-helper-example-debug")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.39-file-aggregator-example-debug")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.39-file-helper-example-debug")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/stats/examples/CMakeLists.txt;0;")
