# CMake generated Testfile for 
# Source directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket
# Build directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/cmake-cache/examples/socket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-socket-bound-static-routing "ns3.39-socket-bound-static-routing-debug")
set_tests_properties(ctest-socket-bound-static-routing PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/examples/socket/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;1;build_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-bound-tcp-static-routing "ns3.39-socket-bound-tcp-static-routing-debug")
set_tests_properties(ctest-socket-bound-tcp-static-routing PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/examples/socket/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;11;build_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv4 "ns3.39-socket-options-ipv4-debug")
set_tests_properties(ctest-socket-options-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/examples/socket/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;22;build_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv6 "ns3.39-socket-options-ipv6-debug")
set_tests_properties(ctest-socket-options-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/examples/socket/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1812;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;32;build_example;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/examples/socket/CMakeLists.txt;0;")
