# CMake generated Testfile for 
# Source directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch
# Build directory: /home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_alternative-topology "ns3.39-alternative-topology-debug")
set_tests_properties(ctest-scratch_alternative-topology PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/scratch/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;57;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;69;create_scratch;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_one-intermediate "ns3.39-one-intermediate-debug")
set_tests_properties(ctest-scratch_one-intermediate PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/scratch/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;57;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;69;create_scratch;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.39-scratch-simulator-debug")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/scratch/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;57;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;69;create_scratch;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_three-intermediate "ns3.39-three-intermediate-debug")
set_tests_properties(ctest-scratch_three-intermediate PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/scratch/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;57;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;69;create_scratch;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.39-scratch-subdir-debug")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;57;build_exec;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;99;create_scratch;/home/teacup/IN3260-measuring-multi-hop-queuing-delay/ns-allinone-3.39/ns-3.39/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
