# CMake generated Testfile for 
# Source directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples
# Build directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/cmake-cache/src/internet/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-main-simple "ns3.39-main-simple-debug")
set_tests_properties(ctest-main-simple PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples/CMakeLists.txt;1;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-example "ns3.39-neighbor-cache-example-debug")
set_tests_properties(ctest-neighbor-cache-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples/CMakeLists.txt;10;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-dynamic "ns3.39-neighbor-cache-dynamic-debug")
set_tests_properties(ctest-neighbor-cache-dynamic PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples/CMakeLists.txt;20;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/internet/examples/CMakeLists.txt;0;")
