# CMake generated Testfile for 
# Source directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples
# Build directory: /Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/cmake-cache/src/uan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-uan-cw-example "ns3.39-uan-cw-example-debug")
set_tests_properties(ctest-uan-cw-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-rc-example "ns3.39-uan-rc-example-debug")
set_tests_properties(ctest-uan-rc-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-ipv4-example "ns3.39-uan-ipv4-example-debug")
set_tests_properties(ctest-uan-ipv4-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-ipv6-example "ns3.39-uan-ipv6-example-debug")
set_tests_properties(ctest-uan-ipv6-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-raw-example "ns3.39-uan-raw-example-debug")
set_tests_properties(ctest-uan-raw-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-6lowpan-example "ns3.39-uan-6lowpan-example-debug")
set_tests_properties(ctest-uan-6lowpan-example PROPERTIES  WORKING_DIRECTORY "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1584;add_test;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;24;build_lib_example;/Users/stianhs/Documents/5.sem/IN3260/queuing_delay/ns-allinone-3.39/ns-3.39/src/uan/examples/CMakeLists.txt;0;")
